name: CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Nix
      uses: cachix/install-nix-action@v23
      # with:
      #   nix_path: nixpkgs=channel:nixos-unstable
    - name: Install direnv
      uses: aldoborrero/direnv-nix-action@v2
      with:
        use_nix_profile: true
        nix_channel: nixpkgs
    - name: make
      run: make
    - name: nix build
      run: nix build
    - name: Check for unverified assumptions
      # https://coq.inria.fr/refman/language/core/assumptions.html#assumptions
      run: MATCH='Admitted\|Axiom\|Axioms\|Conjecture\|Conjectures\|Parameter\|Parameters\|Hypothesis\|Hypotheses\|Variable\|Variables' for f in $(find . -name '*.v'); do if grep -q ${MATCH} ${f}; then grep -Rnw theories -e ${MATCH}; exit 1; fi; done
    - name: Check for trailing whitespace
      run: for f in $(find . -name '*.v'); do if grep -q '.* $' ${f}; then grep -Rnw theories -e '.* $'; exit 1; fi; done
